colors.settings:
  type: config_object
  label: 'Default global color settings'
  mapping:
    label:
      type: string
      label: 'Label'
    override:
      type: boolean
      label: 'Override order of CSS processing'
    order:
      type: sequence
      label: 'Order of CSS processing'
    fields:
      type: sequence
      label: 'Color labels used in palettes'
      sequence:
        type: string
    palette:
      type: sequence
      label: 'Palette settings'
      sequence:
        type: color_hex
# colors.node.article
# colors.user.1234
# colors.user_role.administrator
# colors.vocabulary.tags
colors.*.*:
  type: config_object
  label: 'Colors settings'
  mapping:
    type:
      type: string
      label: 'Type'
    label:
      type: string
      label: 'Label'
    enabled:
      type: boolean
      label: 'Status of setting'
    palette:
      type: sequence
      label: 'Palette settings'
      sequence:
        type: color_hex
    weight:
      type: integer
      label: 'Weight'
